FROM alpine:3.20@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0 as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:fe7714849adfd251129be75e39c5c4fa7031d87146645afa5d391ab957845c18

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
