name: Check dependencies

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'envoyproxy/envoy'
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run dependency checker
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          bazel run //tools/dependency:check -- -c release_issues --fix
          bazel run //tools/dependency:check -- -c cves -w error
